<?php
if ( ! defined( 'ABSPATH' ) ) exit;

if ( ! class_exists( 'WP_List_Table' ) ) { require_once( ABSPATH . 'wp-admin/includes/class-wp-list-table.php' ); }

class CXD_Planes_List_Table extends WP_List_Table {
    public function __construct() { parent::__construct( ['singular' => 'Producto', 'plural' => 'Productos', 'ajax' => false] ); }
    public function get_columns() { return [ 'cb' => '<input type="checkbox" />', 'imagen' => 'Imagen', 'name' => 'Nombre', 'stock' => 'Stock', 'precio_venta' => 'Precio Venta', 'fecha_ultima_modificacion' => 'Últ. Mod. Precio', 'costo_base' => 'Costo Base (PxD)', 'planes_pago' => 'Planes de Pago por Día' ]; }
    public function get_sortable_columns() { return [ 'name' => ['name', false], 'precio_venta' => ['price', false], 'stock' => ['stock', false] ]; }
    protected function extra_tablenav( $which ) { if ( 'top' !== $which ) return; $category_id = isset($_GET['product_cat_filter']) ? absint($_GET['product_cat_filter']) : 0; $stock_status = isset($_GET['stock_status_filter']) ? sanitize_text_field($_GET['stock_status_filter']) : ''; echo '<div class="alignleft actions">'; wp_dropdown_categories(['show_option_all' => 'Todas las categorías', 'taxonomy' => 'product_cat', 'name' => 'product_cat_filter', 'orderby' => 'name', 'selected' => $category_id, 'hierarchical' => true, 'show_count' => false, 'hide_empty' => true]); echo '<select name="stock_status_filter">'; echo '<option value="">Todo el stock</option>'; echo '<option value="instock"' . selected($stock_status, 'instock', false) . '>Con Stock</option>'; echo '<option value="outofstock"' . selected($stock_status, 'outofstock', false) . '>Sin Stock</option>'; echo '</select>'; submit_button('Filtrar', 'button', false, false, ['id' => 'post-query-submit']); echo '</div>'; }
    public function prepare_items() { $this->_column_headers = [ $this->get_columns(), [], $this->get_sortable_columns() ]; $per_page = 20; $current_page = $this->get_pagenum(); $args = [ 'post_type' => 'product', 'posts_per_page' => $per_page, 'paged' => $current_page, 'post_status' => 'publish', 'tax_query' => [] ]; if ( ! empty( $_REQUEST['s'] ) ) { $args['s'] = sanitize_text_field( $_REQUEST['s'] ); } if ( ! empty( $_GET['product_cat_filter'] ) ) { $args['tax_query'][] = [ 'taxonomy' => 'product_cat', 'field' => 'term_id', 'terms' => absint($_GET['product_cat_filter']) ]; } if ( ! empty( $_GET['stock_status_filter'] ) ) { if (empty($args['meta_query'])) { $args['meta_query'] = []; } $args['meta_query'][] = [ 'key' => '_stock_status', 'value' => sanitize_text_field($_GET['stock_status_filter']) ]; } $query = new WP_Query( $args ); $this->items = $query->posts; $this->set_pagination_args( ['total_items' => $query->found_posts, 'per_page' => $per_page] ); $request_uri = $_SERVER['REQUEST_URI']; if ( ! empty( $_REQUEST['s'] ) ) { $request_uri = add_query_arg( 's', sanitize_text_field( $_REQUEST['s'] ), $request_uri ); } if ( ! empty( $_GET['product_cat_filter'] ) ) { $request_uri = add_query_arg( 'product_cat_filter', absint( $_GET['product_cat_filter'] ), $request_uri ); } if ( ! empty( $_GET['stock_status_filter'] ) ) { $request_uri = add_query_arg( 'stock_status_filter', sanitize_text_field( $_GET['stock_status_filter'] ), $request_uri ); } $_SERVER['REQUEST_URI'] = $request_uri; }
    public function column_default( $item, $column_name ) { return 'N/A'; }
    public function column_cb( $item ) { return sprintf( '<input type="checkbox" name="product_id[]" value="%s" />', $item->ID ); }
    public function column_imagen( $item ) { $product = wc_get_product( $item->ID ); return $product ? $product->get_image('thumbnail') : ''; }
    public function column_name( $item ) { $edit_link = get_edit_post_link( $item->ID ); $actions = ['edit' => sprintf( '<a href="%s">Editar</a>', $edit_link ), 'view' => sprintf( '<a href="%s" target="_blank">Ver</a>', get_permalink( $item->ID ) )]; return sprintf( '<strong>%1$s</strong>%2$s', $item->post_title, $this->row_actions( $actions ) ); }
    public function column_precio_venta( $item ) { $product = wc_get_product( $item->ID ); return $product ? $product->get_price_html() : 'N/A'; }
    public function column_fecha_ultima_modificacion( $item ) { $fecha = get_post_meta( $item->ID, 'fecha_ultima_modificacion', true ); if ( ! empty( $fecha ) ) { return esc_html( date_i18n( 'd/m/Y H:i', strtotime( $fecha ) ) ); } else { return '—'; } }
    public function column_costo_base( $item ) { $costo_base = get_post_meta( $item->ID, '_costoxd_base', true ); return $costo_base ? wc_price( $costo_base ) : 'No calculado'; }
    public function column_stock( $item ) { $product = wc_get_product( $item->ID ); if (!$product) return 'N/A'; $stock_status = $product->get_stock_status(); $stock_quantity = $product->get_stock_quantity(); if ($stock_status === 'instock') { return '<span style="color:green;">En stock (' . ($stock_quantity ?: '&#8734;') . ')</span>'; } else { return '<span style="color:red;">Agotado</span>'; } }
    public function column_planes_pago( $item ) { $planes = get_post_meta( $item->ID, '_costoxd_planes', true ); if ( empty( $planes ) ) { return 'N/A'; } $output = '<ul style="margin: 0; padding-left: 15px;">'; foreach ( $planes as $dias => $datos ) { $output .= sprintf( '<li><strong>%d días:</strong> %s</li>', $dias, wc_price( $datos['cuota_diaria'] ) ); } $output .= '</ul>'; return $output; }
}

add_action( 'admin_menu', 'cxd_agregar_pagina_visor' );
function cxd_agregar_pagina_visor() { add_menu_page('Visor de Planes PxD', 'Visor de Planes PxD', 'manage_options', 'cxd-visor-planes', 'cxd_renderizar_pagina_visor', 'dashicons-calculator', 25); }
function cxd_renderizar_pagina_visor() { $list_table = new CXD_Planes_List_Table(); $list_table->prepare_items(); ?> <div class="wrap"> <h1 class="wp-heading-inline">Visor de Productos con Planes de Pago por Día</h1> <hr class="wp-header-end"> <form method="get"> <input type="hidden" name="page" value="<?php echo esc_attr( $_REQUEST['page'] ); ?>" /> <?php $list_table->search_box( 'Buscar Productos', 'product' ); ?> <?php $list_table->display(); ?> </form> </div> <?php }